### PR TITLE
Proposed design for the card

### PR DESCRIPTION
**Pull request by sahibardj**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by sahibardj** [comment]
Edited the cards more and changed the hover effect.

**Comment by sahibardj** [comment]
changed layout of cards

**Comment by Ruchita1010** [comment]
Please resolve the conflicts!

**Comment by sahibardj** [comment]
Conflicts resolved and code updated. Github link and profile image added.

**Pull request merged**
